// ZORRO Strategy - Auto-Generated
// Description: {{DESCRIPTION}}
// Date: {{DATE}}
//
// This strategy was generated by ZORRO Strategy Generator Skill
// Ensure backtesting before live trading

#include <default.c>

function run()
{
    // ===== CONFIGURATION =====
    BarPeriod = {{BARPERIOD}};                    // Candle size in minutes
    StartDate = {{STARTDATE}};                    // Start date YYYYMMDD
    EndDate = {{ENDDATE}};                        // End date YYYYMMDD
    asset("{{ASSET}}");                           // Trading instrument
    LookBack = {{LOOKBACK}};                      // Historical bars needed

    set(PLOTNOW|LOGFILE);                         // Plot and log results

    // ===== SERIES (Price data) =====
    vars Close = series(priceClose());            // Close price series
    vars High = series(priceHigh());              // High price series
    vars Low = series(priceLow());                // Low price series

    // ===== INDICATORS =====
    {{INDICATORS}}

    // ===== RISK MANAGEMENT =====
    {{RISK_MANAGEMENT}}

    // ===== ENTRY LOGIC =====
    {{ENTRY_LOGIC}}

    // ===== EXIT LOGIC =====
    {{EXIT_LOGIC}}
}
